# CodeRabbit Configuration File
# Documentation: https://coderabbit.ai/docs/configure-coderabbit

language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  auto_review:
    enabled: true
    drafts: false
  itemized_feedback:
    enabled: true
chat:
  auto_reply: true
