-- Add realistic seed data
INSERT INTO profiles (name, age, gender, location, occupation, height, education, imageUrl, isVerified, religion, caste, bio, family, preferences, images, email, created_at, last_active) VALUES
('Samanthika', 24, 'Woman', 'Colombo', 'Software Engineer', '5'' 4"', 'Bachelors', 'https://randomuser.me/api/portraits/women/44.jpg', TRUE, 'Buddhist', 'Govigama', 'Tech enthusiast who loves travel and photography.', 'Small family of 4.', 'Looking for someone with similar interests.', '["https://randomuser.me/api/portraits/women/44.jpg"]', 'samanthika@example.com', '2023-10-01 10:00:00', '2023-10-27 10:00:00'),
('Nuwan', 28, 'Man', 'Kandy', 'Doctor', '5'' 9"', 'MBBS', 'https://randomuser.me/api/portraits/men/32.jpg', TRUE, 'Buddhist', 'Radala', 'Dedicated doctor, love hiking on weekends.', 'Respectable family from Kandy.', 'Looking for a kind partner.', '["https://randomuser.me/api/portraits/men/32.jpg"]', 'nuwan@example.com', '2023-10-02 11:30:00', '2023-10-27 11:00:00'),
('Dilani', 26, 'Woman', 'Galle', 'Teacher', '5'' 2"', 'Diploma', 'https://randomuser.me/api/portraits/women/68.jpg', FALSE, 'Christian', 'Karava', 'Passionate teacher, love reading and music.', 'Loving parents and one brother.', 'Looking for an educated partner.', '["https://randomuser.me/api/portraits/women/68.jpg"]', 'dilani@example.com', '2023-10-05 09:15:00', '2023-10-26 15:00:00'),
('Kasun', 30, 'Man', 'Negombo', 'Businessman', '5'' 11"', 'High School', 'https://randomuser.me/api/portraits/men/85.jpg', TRUE, 'Catholic', 'Karava', 'Self-made businessman. Car enthusiast.', 'Business family.', 'Looking for a supportive partner.', '["https://randomuser.me/api/portraits/men/85.jpg"]', 'kasun@example.com', '2023-10-10 14:20:00', '2023-10-27 09:30:00'),
('Chamari', 29, 'Woman', 'Anuradhapura', 'Banker', '5'' 5"', 'Bachelors', 'https://randomuser.me/api/portraits/women/22.jpg', TRUE, 'Buddhist', 'Govigama', 'Ambitious banker. Love cooking.', 'Traditional family.', 'Looking for a professional.', '["https://randomuser.me/api/portraits/women/22.jpg"]', 'chamari@example.com', '2023-10-12 16:45:00', '2023-10-25 18:00:00'),
('Asanka', 32, 'Man', 'Matara', 'Engineer', '5'' 8"', 'Masters', 'https://randomuser.me/api/portraits/men/54.jpg', FALSE, 'Buddhist', 'Durava', 'Civil engineer working on big projects.', 'Parents are retired teachers.', 'Looking for a family-oriented partner.', '["https://randomuser.me/api/portraits/men/54.jpg"]', 'asanka@example.com', '2023-10-15 08:00:00', '2023-10-24 20:00:00'),
('Priya', 23, 'Woman', 'Jaffna', 'Student', '5'' 3"', 'Undergraduate', 'https://randomuser.me/api/portraits/women/91.jpg', FALSE, 'Hindu', 'Vellalar', 'Final year student. Love dancing.', 'Strict but loving family.', 'Looking for a partner from same background.', '["https://randomuser.me/api/portraits/women/91.jpg"]', 'priya@example.com', '2023-10-18 12:10:00', '2023-10-27 12:00:00'),
('Rohan', 35, 'Man', 'Colombo', 'Architect', '6'' 0"', 'Masters', 'https://randomuser.me/api/portraits/men/11.jpg', TRUE, 'Christian', 'Burgher', 'Creative architect. Love art and travel.', 'Modern family.', 'Looking for an open-minded partner.', '["https://randomuser.me/api/portraits/men/11.jpg"]', 'rohan@example.com', '2023-10-20 10:30:00', '2023-10-27 14:00:00'),
('Ishara', 27, 'Woman', 'Kurunegala', 'Nurse', '5'' 4"', 'Diploma', 'https://randomuser.me/api/portraits/women/56.jpg', TRUE, 'Buddhist', 'Govigama', 'Caring nurse. Love pets.', 'Farming family.', 'Looking for a kind-hearted partner.', '["https://randomuser.me/api/portraits/women/56.jpg"]', 'ishara@example.com', '2023-10-22 13:00:00', '2023-10-26 10:00:00'),
('Mahesh', 31, 'Man', 'Gampaha', 'Accountant', '5'' 7"', 'CIMA', 'https://randomuser.me/api/portraits/men/45.jpg', TRUE, 'Buddhist', 'Govigama', 'Professional accountant. Quiet and reserved.', 'Middle class family.', 'Looking for a simple girl.', '["https://randomuser.me/api/portraits/men/45.jpg"]', 'mahesh@example.com', '2023-10-25 09:00:00', '2023-10-27 08:00:00');
